parameters:
  nb_servers: 3

server0:
  address: localhost
  port_server: 12345
  port_client: 12346

server1:
  address: localhost
  port_server: 12347
  port_client: 12348

server2:
  address: localhost
  port_server: 12349
  port_client: 12340