version: "3.9"  # optional since v1.27.0
services:
  server:
    build: server
  client:
    build: client 
    depends_on: 
      - server

#networks:
#  default:
#    external: true
#    name: host
